Update to sync to RWXROB master

diff --git a/snippets/sh/compc b/snippets/sh/compc
--- a/snippets/sh/compc
+++ b/snippets/sh/compc
@@ -1,16 +1,21 @@
 #!/usr/bin/bash
 # shellcheck disable=SC2016
 set -e
+export PATH="/usr/bin:/usr/local/bin"
 
 # Copyright 2021 Rob Muhlestein <rob@rwx.gg>
 # Released under Apache-2.0 license
 # Please mention https://youtube.com/rwxrob
 
-: ${PAGER:=more}
-: ${EDITOR:=vi}
+(( BASH_VERSINFO[0] < 4 )) && echo "Bash 4+ required." && exit 1
+
+: "${PAGER:=more}"
+: "${EDITOR:=vi}"
+: "${HELP_BROWSER:=}"
+
 EXE="${0##*/}"
 
-declare -A help
+declare -A help # associative arrays *require* declaration
 
 help[main]='
 This snippet contains the scaffolding for Bash tab completion using
@@ -20,27 +25,40 @@ use it simply add a function with the additional command and add the
 name of it to the commands array declaration at the top of the script.
 Then add complete -C foo foo (or something like it) to your bashrc.
 Begin functions with x_ to allow useful command names to be used that
-would otherwise conflict with existing system and bash keywords.
+would otherwise conflict with existing system and bash keywords. Begin
+functions with x__ when you do not want them to appear with tab
+completion, but still want them to be avaiable, just hidden.
 '
 
+help[foo]='The `foo` command foos.'
+
 x_foo() {
-  _filter "$@"
+  _filter "$@" && return $?
   echo "would foo: $*"
 }
 
-x_foo_bar() {
-  _filter "$@"
-  echo "would foo bar: $*"
+help[bar]='The `bar` command bars.'
+
+x_bar() {
+  _filterbuf "$@" && return $?
+  echo "would bar: $*"
 }
 
 x__hidden() {
-  _filter "$@"
+  _filter "$@" && return $?
   echo "would run _hidden: $*"
 }
 
+help[usage]='The `usage` command displays a summary of usage.'
+
 x_usage() {
-    local cmds="${COMMANDS[*]}"
-    printf "usage: %s (%s)\n" "${0##*/}" "${cmds// /|}"
+  local -a cmds
+  for c in "${COMMANDS[@]}"; do
+    [[ ${c:0:1} =~ _ ]] && continue
+    cmds+=($c)
+  done
+  cmds="${cmds[*]}"
+  printf "usage: %s (%s)\n" "$EXE" "${cmds// /|}"
 }
 
 help[help]='
@@ -65,7 +83,7 @@ x_help() {
   [[ $name = main ]] && title="$EXE"
   local file="/tmp/help-$EXE-$name.html"
   if _have pandoc ; then
-    if _have "$HELP_BROWSER" ;then
+    if _have "$HELP_BROWSER" && [[ -t 1 ]] ;then
       pandoc -s --metadata title="$title" \
         -o "$file" <<< "${help[$name]}"
       [[ -z "$2" ]] && cd /tmp && exec "$HELP_BROWSER" "$file"
@@ -83,38 +101,45 @@ x_help() {
 _have(){ type "$1" &>/dev/null; }
 
 _filter(){
-  (( $# > 0 )) && return 0
+  [[ -n "$1" ]] && return 1
   while IFS= read -ra args; do
     "${FUNCNAME[1]}" "${args[@]}"
   done
 }
 
+_filterbuf() {
+  [[ -n "$1" ]] && return 1
+  "${FUNCNAME[1]}" "$(</dev/stdin)"
+}
+
 while IFS= read -r line; do
-    [[ $line =~ ^declare\ -f\ x_ ]] || continue
-    COMMANDS+=( "${line##declare -f x_}" )
+  [[ $line =~ ^declare\ -f\ x_ ]] || continue
+  COMMANDS+=( "${line##declare -f x_}" )
 done < <(declare -F)
 
 if [[ -n $COMP_LINE ]]; then
-    line=${COMP_LINE#* }
-    for c in "${COMMANDS[@]}"; do
-        [[ ${c:0:${#line}} == "${line,,}" && ${c:1:1} != _ ]] && echo "$c"
-    done
-    exit
+  line=${COMP_LINE#* }
+  for c in "${COMMANDS[@]}"; do
+    [[ ${c:0:${#line}} == "${line,,}" && ${c:0:1} != _ ]] && echo "$c"
+  done
+  exit
 fi
 
 for c in "${COMMANDS[@]}"; do
-    if [[ $c == "$EXE" ]]; then
-        "x_$EXE" "$@"
-        exit $?
-    fi
+  if [[ $c == "$EXE" ]]; then
+    "x_$EXE" "$@"
+    exit $?
+  fi
 done
 
-declare cmd="$1"; shift
-for c in "${COMMANDS[@]}"; do
+if [[ -n "$1" ]]; then
+  declare cmd="$1"; shift
+  for c in "${COMMANDS[@]}"; do
     if [[ $c == "$cmd" ]]; then
-        "x_$cmd" "$@"
-        exit $?
+      "x_$cmd" "$@"
+      exit $?
     fi
-done
+  done
+fi
 
 x_usage "$@"
