Add zet video update to sync

diff --git a/scripts/zet b/scripts/zet
--- a/scripts/zet
+++ b/scripts/zet
@@ -48,12 +48,28 @@ _usage() {
     printf "usage: ${0##*/} (${cmds// /|})\n"
 }
 
+_set_video() {
+  local dir="$(_d)/$1"
+  local readme="$dir/README.md"
+  [[ ! -r $readme ]] && echo "<not found>" && return 1
+  if [[ $(sed '3q;d' "$readme") =~ ^📺 ]]; then
+    echo -e "3c\n📺 <$2>\n.\nwq" | ed "$readme" >/dev/null
+  else
+    echo -e "2a\n📺 <$2>\n\n.\nwq" | ed "$readme" >/dev/null
+  fi
+}
+
 _video() {
   local zet="$1"
+  local vid="$2"
+  if [[ -n "$vid" ]]; then
+    _set_video "$@"
+    return $?
+  fi
   local IFS=$'\n'
   if [[ -z $zet ]]; then
     while read -r line; do
-      _video "$line"
+      _video $line
     done
     return 0
   fi
@@ -61,7 +77,10 @@ _video() {
   local readme="$dir/README.md"
   [[ ! -r $readme ]] && echo "<not found>" && return 1
   while read -r line; do
-    [[ $line =~ ^📺\  ]] && echo "${line#* }" && return 0
+    if [[ $line =~ ^📺\ \<(.*)\> ]]; then
+      echo "${BASH_REMATCH[1]}"
+      return 0
+    fi
   done < "$readme"
   return 1
 }
