Improve zet and yt

diff --git a/scripts/zet b/scripts/zet
--- a/scripts/zet
+++ b/scripts/zet
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/bash
 set -e
 
 # This zet script is a multicall executable, which means you may have
@@ -30,67 +30,162 @@ EXE=${0##*/}
 test -z "$EXE" && echo "Could not determine name of executable." && exit 1
 DIR="$ZETDIR/$EXE"
 
-# ------------------------- complete context -------------------------
-
-declare -a COMMANDS=(usage a add q query text d dir e edit id urlencode ls titles last title body before after ids video for rm remove v view)
-
-if [[ -n $COMP_LINE ]]; then
-    for c in "${COMMANDS[@]}"; do
-        [[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
-    done
-    exit
-fi
-
 # ----------------------------- commands -----------------------------
 
-_usage() {
+# Each reads the arguments as a template for a command to be passed to
+# the command line. The syntax of the template uses Go templates (as
+# popularized by Kubernetes). The following values can be wrapped in
+# double curly brackets to be replaced before being called. If a value
+# is emply the word 'null' will be replaced. By default, all markdown is
+# converted into text with the pandoc command:
+#
+#   {{.ID}}          - isosec identifier
+#   {{.Title}}       - full (converted) text of title
+#   {{.Body}}        - all text (converted) but title and video
+#   {{.Slug}}        - dashed slug derived from title
+#   {{.Video}}       - full video URL (usually https://youtu.be/...)
+#   {{.File.Dir}}    - full path to the zettel directory
+#   {{.File.README}} - full path to the README.md file
+#   {{.File.Data}}   - full path to the data.yaml file (even if not exists)
+#   {{.Web.Dir}}     - curl-able URL to the zettel directory
+#   {{.Web.README}}  - curl-able URL to raw README.md file
+#   {{.Web.Data}}    - curl-able URL to raw data.yaml file
+#   {{.Data.*}}      - reference to data from the parsed data.yaml file
+#   {{.Raw.Title}}   - raw markdown of title (including initial #)
+#   {{.Raw.Body}}    - raw markdown of body
+#   {{.Raw.README}}  - raw markdown entire README.md file
+#   {{.Raw.Data}}    - raw YAML from data.yaml file
+#
+# The order is always sorted by isosec meaning that the newest will
+# always be last.
+
+x_each() {
+  if [[ $# == 0 ]];then
+    x_each "echo"
+    return $?
+  fi
+  local dir=$(x_d)
+  for i in $(x_ids); do
+    "$@" "$dir/$i/README.md"
+  done
+}
+
+# Grep is simply a shortcut for `zet each grep "$@"` running the system
+# grep on all the main zettel README.md files passing the arguments
+# as-is to the grep command (-P for PRCE, etc.)
+
+x_grep() {
+  x_each grep "$@"
+}
+
+x_open() {
+  local zetid="$1"
+  [[ -z "$zetid" || $zetid = last ]] && zetid=$(x_last)
+  open "https://github.com/rwxrob/zet/tree/main/$zetid"
+}
+
+x_usage() {
     local cmds="${COMMANDS[@]}"
     printf "usage: ${0##*/} (${cmds// /|})\n"
 }
 
-_set_video() {
-  local dir="$(_d)/$1"
-  local readme="$dir/README.md"
-  [[ ! -r $readme ]] && echo "<not found>" && return 1
-  if [[ $(sed '3q;d' "$readme") =~ ^📺 ]]; then
-    echo -e "3c\n📺 <$2>\n.\nwq" | ed "$readme" >/dev/null
-  else
-    echo -e "2a\n📺 <$2>\n\n.\nwq" | ed "$readme" >/dev/null
-  fi
-}
+x_commit() {
 
-_video() {
-  local zet="$1"
-  local vid="$2"
-  if [[ -n "$vid" ]]; then
-    _set_video "$@"
-    return $?
-  fi
+  # recurse if called as filter
   local IFS=$'\n'
-  if [[ -z $zet ]]; then
+  if [[ -z "$1" ]]; then
     while read -r line; do
-      _video $line
+      x_commit $line
     done
     return 0
   fi
-  local dir="$(_d)/$1"
+
+  # if no zet, bail
+  local dir="$(x_d)/$1"
   local readme="$dir/README.md"
-  [[ ! -r $readme ]] && echo "<not found>" && return 1
-  while read -r line; do
-    if [[ $line =~ ^📺\ \<(.*)\> ]]; then
-      echo "${BASH_REMATCH[1]}"
-      return 0
-    fi
-  done < "$readme"
-  return 1
+  [[ ! -r $readme ]] && echo "<not found: $1>" && return 1
+
+  # git commit keeping title as commit message 
+  local title=$(x_title)
+  cd "$dir"
+  pwd
+  echo -n "... "
+  git add -A "$dir" &>/dev/null
+  git commit -m "$title" &>/dev/null || true
+  git push &>/dev/null
+  echo Commited.
+  cd -
+
 }
 
-_urlencode() {
+x_video() {
+
+  # recurse if called as filter
+  local IFS=$'\n'
+  if [[ -z "$1" ]]; then
+    while read -r line; do
+      x_video $line
+    done
+    return 0
+  fi
+
+  # accept zet or yt ids  
+  local zetid ytid changed
+  if [[ $1 =~ ^[0-9]{14,}$ ]]; then
+    zetid="$1"
+    ytid="${2##*/}"
+  elif [[ $1 = last ]]; then
+    zetid=$(x_last)
+    ytid="${2##*/}"
+  else
+    ytid="${1##*/}"
+    zetid=$(yt zet "$1")
+  fi
+
+  # if no zet, bail
+  local dir="$(x_d)/$zetid"
+  local readme="$dir/README.md"
+  [[ ! -r $readme ]] && echo "<not found: $zetid/$ytid>" && return 1
+
+  # if zet has vid line...
+  if [[ $(sed '3q;d' "$readme") =~ ^📺\ \<https://youtu.be/(.*)\> ]]; then
+
+    # update if ytid 
+    if [[ -n "$ytid" ]]; then
+      echo -e "3c\n📺 <https://youtu.be/$ytid>\n.\nwq" | ed "$readme" >/dev/null
+      changed=1
+
+    # read it to print later
+    else
+      ytid=${BASH_REMATCH[1]}
+    fi
+
+  # zet does not have vid line
+  else
+
+    # so add it if have video id
+    if [[ -n "$ytid" ]]; then
+      echo -e "2a\n📺 <https://youtu.be/$ytid>\n\n.\nwq" | ed "$readme" >/dev/null
+      changed=1
+    fi
+  fi
+
+  # always print the url to the video id
+  if [[ -n "$ytid" ]]; then
+    echo "https://youtu.be/$ytid"
+    [[ $changed = 1 ]] && x_commit "$zetid"
+  else
+    echo "<no video found in $zetid>"
+  fi
+}
+x_v() { x_video "$@"; }
+
+x_urlencode() {
   local string="$*"
   if [[ -z $string ]]; then
     local IFS=$'\n'
     while read -r line; do
-      _urlencode "$line"
+      x_urlencode "$line"
     done
   fi
   local strlen=${#string}
@@ -107,10 +202,10 @@ _urlencode() {
   echo "${encoded}"
 }
 
-_id() { date -u +%Y%m%d%H%M%S; }
+x_id() { date -u +%Y%m%d%H%M%S; }
 
-_dir() { [[ -d $DIR ]] && echo "$DIR"; }
-_d() { _dir "$@"; }
+x_dir() { [[ -d $DIR ]] && echo "$DIR"; }
+x_d() { x_dir "$@"; }
 
 # Add creates a Zettelkasten repo entry with an isosec unique directory
 # name within the $KN/$EXE parent directory. Whatever the effective name
@@ -121,8 +216,8 @@ _d() { _dir "$@"; }
 # commiting and pushing to main/master is allowed (which is usually fine
 # for knowledge repos).
 
-_add() {
-  local dir="$(_d)/$(_id)"
+x_add() {
+  local dir="$(x_d)/$(x_id)"
   local readme="$dir/README.md"
   mkdir -p "$dir"
   "${EDITOR:-vim}" "$readme"
@@ -131,24 +226,36 @@ _add() {
   line=$(head -1 "$dir/README.md" | sed 's/#\+ *//')
   test -n "$line"
   echo "Adding: $line"
-  git add -A "$dir"
-  git commit -m "$line"
-  git push
+  git add -A "$dir" &>/dev/null
+  git commit -m "$line" &>/dev/null
+  git push &>/dev/null
 }
-_a() { _add "$@"; }
+x_a() { x_add "$@"; }
 
-_edit() {
-  local dir="$(_d)/$1"
+x_edit() {
+  local dir
+  if [[ $1 =~ ^[0-9]{14,}$ ]]; then
+    dir="$(x_d)/$1"
+  elif [[ $1 = last ]]; then
+    dir="$(x_d)/$(x_last)"
+  else
+    local zetid=$(yt zet "$1")
+    if [[ -z "$zetid" ]]; then
+      echo "Unable to determine zet id for $1"
+      return 1
+    fi
+    dir="$(x_d)/$zetid"
+  fi
   local readme="$dir/README.md"
   [[ ! -r $readme ]] && echo "Not found." && return 1
   "${EDITOR:-vim}" "$readme"
   # TODO prompt for "save" (git commit)
 }
-_e() { _edit "$@"; }
+x_e() { x_edit "$@"; }
 
-_titles() {
-  local dir=$(_d)
-  local -a zets=($(find "$dir" -maxdepth 2 -type d -path '*/20*'|sort ))
+x_titles() {
+  local dir=$(x_d)
+  local -a zets=($(find "$dir" -maxdepth 2 -type d -path '*/2*'|sort ))
   local IFS=$'\n'
   local buf
   for i in ${zets[@]}; do
@@ -160,15 +267,18 @@ _titles() {
   done
   pandoc -t plain --wrap=none <<< "$buf"
 }
-_ls() { _titles "$@"; }
+x_ls() { x_titles "$@"; }
 
-_last() {
-  local line=$(_titles | tail -1)
-  echo "* [${line#* }](https://github.com/rwxrob/zet/tree/main/${line%% *})"
+x_last() {
+  local IFS=$'\n'
+  local -a titles=($(x_titles))
+  local last=${#titles[@]}
+  echo "${titles[$last-1]%% *}"
+  #echo "* [${line#* }](https://github.com/rwxrob/zet/tree/main/${line%% *})"
 }
 
-_text() {
-  local dir="$(_d)/$1"
+x_text() {
+  local dir="$(x_d)/$1"
   local readme="$dir/README.md"
   [[ -r $readme ]] || return 1
   local pandoc=$(command -v pandoc)
@@ -176,8 +286,8 @@ _text() {
   pandoc -t plain --wrap=none < "$readme"
 }
 
-_title() {
-  local dir="$(_d)/$1"
+x_title() {
+  local dir="$(x_d)/$1"
   [[ -d $dir ]] || return 1
   local readme="$dir/README.md"
   read -r title < $readme
@@ -185,44 +295,78 @@ _title() {
   pandoc -t plain --wrap=none <<< "${title#\# }"
 }
 
-_body() {
-  local dir="$(_d)/$1"
+x_body() {
+  local dir="$(x_d)/$1"
   [[ -d $dir ]] || return 1
   local readme="$dir/README.md"
   local buf=$(<$readme)
   local eol=$'\n'
-  [[ $buf =~ ^\#\  ]] && buf=${buf#*$eol$eol}
+  [[ $buf =~ ^\#\  ]] && buf=${buf#*$eol$eol} 
   buf=${buf#📺 *$eol$eol}
   pandoc -t plain --wrap=none <<< "$buf"
 }
 
-_query() {
+x_query() {
   [[ -z "$1" ]] && echo "Missing search query." && return 1
   term="$*"
-  it="https://github.com/$GITUSER/$EXE/search?q=$(_urlencode $term)"
+  it="https://github.com/$GITUSER/$EXE/search?q=$(x_urlencode $term)"
   echo "[$term]: <$it>"
   local chat=$(command -v chat)
   [[ -z $chat ]] && return 0
   exec chat "$it"
 }
-_q() { _query "$@"; }
+x_q() { x_query "$@"; }
 
-_remove() {
-  local dir=$(_d)
+x_ids() {
+  while read -r line; do
+    echo "${line##*/}"
+  done < <(find "$(x_d)" -maxdepth 2 -type d -path '*/2*'| sort)
+}
+
+x_before() {
+  local id=$1
+  local prev
+  while read -r cur; do
+    (( $cur > $id )) && break
+    prev=$cur
+  done < <(x_ids)
+  echo $prev
+}
+
+x_for() {
+  local mkv="$1"
+  [[ $mkv == last ]] && mkv=$(mkvlast)
+  [[ $mkv =~ - ]] && mkv=$(mkv2isosec "$mkv")
+  local id=${mkv##*/}
+  id=${id%.mkv}
+  zet before $id
+}
+
+x_after() {
+  local id=$1
+  while read -r cur; do
+    (( cur > $id )) && break
+  done < <(x_ids)
+  echo $cur
+}
+
+x_remove() {
+  local dir=$(x_d)
   local IFS=$'\n'
   cd "$dir"
   select title in `$EXE titles`; do
     rm -rf "$dir/${title%% *}"
     git add "$dir"
-    git commit -m "done"
-    git push
+    git commit --quiet -m "done"
+    git push --quiet
+    echo "Marked as done"
     exit
   done
 }
-_rm() { _remove "$@"; }
+x_rm() { x_remove "$@"; }
 
-_view() {
-  local dir=$(_d)
+x_view() {
+  local dir=$(x_d)
   local IFS=$'\n'
   cd "$dir"
   select title in `$EXE titles`; do
@@ -230,48 +374,30 @@ _view() {
     exit
   done
 }
-_v() { _view "$@"; }
 
-_ids() {
-  while read -r line; do
-    echo "${line##*/}"
-  done < <(find "$(_d)" -maxdepth 2 -type d -path '*/20*'| sort)
-}
+# --------------------- completion and delegation --------------------
 
-_before() {
-  local id=$1
-  local prev
-  while read -r cur; do
-    (( cur > $id )) && break
-    prev=$cur
-  done < <(_ids)
-  echo $prev
-}
+declare -a COMMANDS=()
 
-_for() {
-  local mkv="$1"
-  [[ $mkv =~ - ]] && mkv=$(mkv2isosec "$1")
-  local id=${mkv##*/}
-  id=${id%.mkv}
-  zet before $id
-}
+while read -r line; do
+    [[ $line =~ ^declare\ -f\ x_ ]] || continue
+    COMMANDS+=( ${line##declare -f x_} )
+done < <(declare -F)
 
-_after() {
-  local id=$1
-  while read -r cur; do
-    (( cur > $id )) && break
-  done < <(_ids)
-  echo $cur
-}
-
-# ---------------------------- delegation ----------------------------
+if [[ -n $COMP_LINE ]]; then
+    for c in "${COMMANDS[@]}"; do
+        [[ ${c:0:${#2}} == "${2,,}" ]] && echo "$c"
+    done
+    exit
+fi
 
 declare cmd="$1"; shift
 for c in "${COMMANDS[@]}"; do
     if [[ $c == "$cmd" ]]; then
-      "_$cmd" "$@"
-      exit $?
+        "x_$cmd" "$@"
+        exit $?
     fi
 done
 
-_usage "$@"
+x_usage "$@"
+
